add nvim

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -1,31 +1,24 @@
 #!/bin/bash
 
+set -eu
 
-echo "Check yadm remote url..."
-github_ssh_url="git@github.com:mslxl/.dotfile.git"
-yadm_url=$(yadm remote get-url origin 2>&1)
-if [[ "$?" != "0" ]]; then
-    echo "Add remote url to $github_ssh_url"
-    yadm remote add origin $github_ssh_url
-elif [[ "$yadm_url" != "$github_ssh_url" ]]; then
-    echo "Set remote url to $github_ssh_url"
-    yadm remote set-url origin $github_ssh_url
+
+BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+
+if [[ ! -d "$BOOTSTRAP_D" ]]; then
+    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    exit 1
 fi
-echo "Done"
 
-
-echo "Check bootstrap depentences..."
-hash amm 2>/dev/null || {
-    echo "ammonite misssing. Installing..."
-    hash pacman 2>/dev/null
-    if [[ "$?" == "0" ]]; then
-        sudo pacman -S ammonite
-    else
-        sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/com-lihaoyi/Ammonite/releases/download/2.5.1/2.13-2.5.1) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'
+find -L "$BOOTSTRAP_D" -type f | grep -v "/ammonite/" | sort | while IFS= read -r bootstrap; do
+    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        echo
+        echo ">>> $(basename $bootstrap) >>>"
+        if ! "$bootstrap"; then
+            echo "Error: bootstrap '$bootstrap' failed" >&2
+            exit 1
+        fi
+        echo "<<< $(basename $bootstrap) <<<"
     fi
-}
-echo "Done"
+done
 
-echo "Execuate ammonite script..."
-amm $HOME/.config/yadm/bootstrap.d/init.sc
-echo "Done"
